name: Build and deploy container app to Azure Web App - ChestCancerClassification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: chestcancerclassification.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chestcancerclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/flaskapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ChestCancerClassification'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: 'chestcancerclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/flaskapp:${{ github.sha }}'
